export const MEMORY_FIELDS = [
  {
    label: 'Enable Memory',
    path: ['capabilities', 'memory', 'enabled'],
    input: 'select' as const,
    options: ['true', 'false'],
    description: 'Controls whether retained memory capability settings are active.',
  },
  {
    label: 'Memory Provider',
    path: ['capabilities', 'memory', 'provider'],
    input: 'select' as const,
    options: ['session', 'local', 'mem0'],
    description: 'Controls where admitted memory records are stored between runs.',
  },
  {
    label: 'Case Memory',
    path: ['capabilities', 'memory', 'scopes', 'case', 'enabled'],
    input: 'select' as const,
    options: ['true', 'false'],
    description: 'Lets the Agent reuse facts from the current case while keeping them out of broader user or shared memory.',
  },
  {
    label: 'Case Retention (days)',
    path: ['capabilities', 'memory', 'scopes', 'case', 'retention_days'],
    input: 'number' as const,
    description: 'Sets how long case-scoped memory remains eligible for retrieval.',
  },
  {
    label: 'Case Max Records',
    path: ['capabilities', 'memory', 'scopes', 'case', 'max_records'],
    input: 'number' as const,
    description: 'Caps how many case memory records can be returned to the Agent context.',
  },
  {
    label: 'Case Allow Restricted',
    path: ['capabilities', 'memory', 'scopes', 'case', 'allow_restricted'],
    input: 'select' as const,
    options: ['true', 'false'],
    description: 'Controls whether restricted memory can be admitted into case context.',
  },
  {
    label: 'User Memory',
    path: ['capabilities', 'memory', 'scopes', 'user', 'enabled'],
    input: 'select' as const,
    options: ['true', 'false'],
    description: 'Enables consent-gated customer memory across cases for the same subject reference.',
  },
  {
    label: 'User Retention (days)',
    path: ['capabilities', 'memory', 'scopes', 'user', 'retention_days'],
    input: 'number' as const,
    description: 'Sets how long user-scoped memory remains eligible for retrieval.',
  },
  {
    label: 'User Max Records',
    path: ['capabilities', 'memory', 'scopes', 'user', 'max_records'],
    input: 'number' as const,
    description: 'Caps how many user memory records can be returned to the Agent context.',
  },
  {
    label: 'User Allow Restricted',
    path: ['capabilities', 'memory', 'scopes', 'user', 'allow_restricted'],
    input: 'select' as const,
    options: ['true', 'false'],
    description: 'Controls whether restricted user memory can be admitted into context.',
  },
  {
    label: 'Shared Memory',
    path: ['capabilities', 'memory', 'scopes', 'shared', 'enabled'],
    input: 'select' as const,
    options: ['true', 'false'],
    description: 'Enables shared memory that can influence more than one user or case.',
  },
]
