const MODEL_PROVIDER_OPTIONS = ['deterministic', 'openai_compatible', 'openai', 'deepseek', 'azure_openai', 'anthropic']

export const MODEL_FIELDS = [
  { label: 'Answer Model Provider', path: ['model', 'provider'], input: 'select' as const, options: MODEL_PROVIDER_OPTIONS, description: 'Provider for final answer generation' },
  { label: 'Answer Model Name', path: ['model', 'name'], input: 'text' as const, description: 'Model identifier for final answers', placeholder: 'deepseek-v4-flash' },
  { label: 'Answer API Key Env', path: ['model', 'params', 'api_key_env'], input: 'text' as const, description: 'Environment variable name only; DeepSeek defaults to DEEPSEEK_API_KEY', placeholder: 'DEEPSEEK_API_KEY' },
  { label: 'Answer Base URL Env', path: ['model', 'params', 'base_url_env'], input: 'text' as const, description: 'Optional proxy/base URL environment variable', placeholder: 'DEEPSEEK_BASE_URL' },
  { label: 'Answer DeepSeek Endpoint', path: ['model', 'params', 'deepseek_endpoint_mode'], input: 'select' as const, options: ['beta', 'standard'], description: 'DeepSeek endpoint mode; beta is the default /beta endpoint' },
  { label: 'Answer Temperature', path: ['model', 'params', 'temperature'], input: 'number' as const, description: 'Optional provider temperature' },
  { label: 'Answer Max Output Tokens', path: ['model', 'params', 'max_output_tokens'], input: 'number' as const, description: 'Optional provider default token cap' },
  { label: 'Answer Timeout (s)', path: ['model', 'params', 'timeout_seconds'], input: 'number' as const, description: 'Optional provider request timeout' },
  { label: 'Max ReAct Steps', path: ['react', 'max_steps'], input: 'number' as const, description: 'Maximum planning and action steps per run' },
  { label: 'Max Tool Calls', path: ['react', 'max_tool_calls'], input: 'number' as const, description: 'Maximum governed tool calls per run' },
  { label: 'Record Reasoning', path: ['react', 'record_reasoning_summary'], input: 'select' as const, options: ['true', 'false'], description: 'Record structured reasoning summary' },
  { label: 'Planner Provider', path: ['react', 'planner', 'provider'], input: 'select' as const, options: MODEL_PROVIDER_OPTIONS, description: 'Provider for ReAct planner' },
  { label: 'Planner Model', path: ['react', 'planner', 'name'], input: 'text' as const, description: 'Model name for ReAct planner', placeholder: 'deepseek-v4-flash' },
  { label: 'Planner API Key Env', path: ['react', 'planner', 'params', 'api_key_env'], input: 'text' as const, description: 'Environment variable name only; DeepSeek defaults to DEEPSEEK_API_KEY', placeholder: 'DEEPSEEK_API_KEY' },
  { label: 'Planner Base URL Env', path: ['react', 'planner', 'params', 'base_url_env'], input: 'text' as const, description: 'Optional proxy/base URL environment variable', placeholder: 'DEEPSEEK_BASE_URL' },
  { label: 'Planner DeepSeek Endpoint', path: ['react', 'planner', 'params', 'deepseek_endpoint_mode'], input: 'select' as const, options: ['beta', 'standard'], description: 'DeepSeek endpoint mode; beta is the default /beta endpoint' },
  { label: 'Planner Temperature', path: ['react', 'planner', 'params', 'temperature'], input: 'number' as const, description: 'Optional provider temperature for planning' },
  { label: 'Planner Max Output Tokens', path: ['react', 'planner', 'params', 'max_output_tokens'], input: 'number' as const, description: 'Optional planner token cap' },
  { label: 'Planner Timeout (s)', path: ['react', 'planner', 'params', 'timeout_seconds'], input: 'number' as const, description: 'Optional planner request timeout' },
  { label: 'Review Mode', path: ['review', 'mode'], input: 'select' as const, options: ['rules_only', 'auto'], description: 'Harness review mode' },
  { label: 'Reviewer Provider', path: ['review', 'subagent', 'provider'], input: 'select' as const, options: MODEL_PROVIDER_OPTIONS, description: 'Provider for review subagent' },
  { label: 'Reviewer Model', path: ['review', 'subagent', 'name'], input: 'text' as const, description: 'Model name for review subagent', placeholder: 'deepseek-v4-flash' },
  { label: 'Reviewer API Key Env', path: ['review', 'subagent', 'params', 'api_key_env'], input: 'text' as const, description: 'Environment variable name only; DeepSeek defaults to DEEPSEEK_API_KEY', placeholder: 'DEEPSEEK_API_KEY' },
  { label: 'Reviewer Base URL Env', path: ['review', 'subagent', 'params', 'base_url_env'], input: 'text' as const, description: 'Optional proxy/base URL environment variable', placeholder: 'DEEPSEEK_BASE_URL' },
  { label: 'Reviewer DeepSeek Endpoint', path: ['review', 'subagent', 'params', 'deepseek_endpoint_mode'], input: 'select' as const, options: ['beta', 'standard'], description: 'DeepSeek endpoint mode; beta is the default /beta endpoint' },
  { label: 'Reviewer Temperature', path: ['review', 'subagent', 'params', 'temperature'], input: 'number' as const, description: 'Optional provider temperature for review' },
  { label: 'Reviewer Max Output Tokens', path: ['review', 'subagent', 'params', 'max_output_tokens'], input: 'number' as const },
  { label: 'Review Timeout (s)', path: ['review', 'subagent', 'params', 'timeout_seconds'], input: 'number' as const },
  { label: 'Review Fail Closed', path: ['review', 'subagent', 'fail_closed'], input: 'select' as const, options: ['true'] },
]
