from __future__ import annotations

from enum import Enum


class ReceiptOutcome(str, Enum):
    ANSWERED_WITH_CITATIONS = "ANSWERED_WITH_CITATIONS"
    REFUSED_NO_EVIDENCE = "REFUSED_NO_EVIDENCE"
    ESCALATED_WEAK_EVIDENCE = "ESCALATED_WEAK_EVIDENCE"
    WAITING_FOR_APPROVAL = "WAITING_FOR_APPROVAL"
    TOOL_APPROVAL_DENIED = "TOOL_APPROVAL_DENIED"
    FAILED_WITH_TRACE = "FAILED_WITH_TRACE"
    FAILED_RECEIPT_UNAVAILABLE = "FAILED_RECEIPT_UNAVAILABLE"
